#!/usr/bin/env bash

#########################################################################
#########################################################################

function get_version_git {

    current_rev=$(git rev-parse HEAD)
    if [[ "$(git show-ref --tags | fgrep $current_rev)" == *releases* ]]; then
	git show-ref --tags | fgrep $current_rev | fgrep releases | cut -d '/' -f 3-4
    elif [[ "$(git show-ref --heads | fgrep $current_rev)" == *stable* ]]; then
	git show-ref --heads | fgrep $current_rev | fgrep stable | cut -d '/' -f 3-4
    elif [ "$(git show-ref --heads | fgrep $current_rev)" != "" ]; then
	git show-ref --heads | fgrep $current_rev | cut -d '/' -f 3
    else
        echo $current_rev
    fi

}

#########################################################################
#########################################################################

function parse_yaml {
    local yaml_file=$1
    local prefix=
    local s
    local w
    local fs

    s='[[:space:]]*'
    w='[a-zA-Z0-9_.-]*'
    fs="$(echo @|tr @ '\034')"

    (
        sed -e '/- [^\“]'"[^\']"'.*: /s|\([ ]*\)- \([[:space:]]*\)|\1-\'$'\n''  \1\2|g' |

        sed -ne '/^--/s|--||g; s|\"|\\\"|g; s/[[:space:]]*$//g;' \
            -e "/#.*[\"\']/!s| #.*||g; /^#/s|#.*||g;" \
            -e "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
            -e "s|^\($s\)\($w\)${s}[:-]$s\(.*\)$s\$|\1$fs\2$fs\3|p" |

        awk -F"$fs" '{
            indent = length($1)/2;
            if (length($2) == 0) { conj[indent]="+";} else {conj[indent]="";}
            vname[indent] = $2;
            for (i in vname) {if (i > indent) {delete vname[i]}}
                if (length($3) > 0) {
                    vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
                    printf("%s%s%s%s=(\"%s\")\n", "'"$prefix"'",vn, $2, conj[indent-1],$3);
                }
            }' |

        sed -e 's/_=/+=/g' |

        awk 'BEGIN {
                FS="=";
                OFS="="
            }
            /(-|\.).*=/ {
                gsub("-|\\.", "_", $1)
            }
            { print }'
    ) < "$yaml_file"
}

#########################################################################
#########################################################################

function create_variables {
    local yaml_file="$1"
    eval "$(parse_yaml "$yaml_file")"
    lower_case=$(echo $Description_Slug | tr '[:upper:]' '[:lower:]')

    version=$(get_version_git)
    version_num=$(echo $version | cut -d '/' -f 2)
}

#########################################################################
#########################################################################

function make_header {
    if [ $version = master ]; then
        echo "# $Description_ShortName"
    else
        echo "# $Description_ShortName $version_num"
    fi
    
    echo "
[![A COIN-OR Project](https://coin-or.github.io/coin-or-badge.png)](https://www.coin-or.org)

[![Latest Release](https://img.shields.io/github/v/release/coin-or/$Description_Slug?sort=semver)](https://github.com/coin-or/$Description_Slug/releases)

_This file is auto-generated from [config.yml](.coin-or/config.yml) using the 
[generate_readme](.coin-or/generate_readme) script.
To make changes, please edit [config.yml](.coin-or/config.yml) or the generation script._
" 
}

#########################################################################
#########################################################################

function make_build_info {
    echo "
$Description_ShortName is written in $Description_Language and is released as open source under the [$Description_License]($Description_LicenseURL).

It is distributed under the auspices of the [COIN-OR Foundation](https://www.coin-or.org)

The $Description_ShortName development site is https://github.com/coin-or/$Description_Slug.

## CITE

[![DOI](https://zenodo.org/badge/$Description_Zenodo.svg)](https://zenodo.org/badge/latestdoi/$Description_Zenodo)

## CURRENT BUILD STATUS

[![Build Status](https://travis-ci.com/coin-or/$Description_Slug.svg?branch=$version)](https://travis-ci.com/coin-or/$Description_Slug)

[![Build status](https://ci.appveyor.com/api/projects/status/$Description_Appveyor_Status/branch/$version?svg=true)](https://ci.appveyor.com/project/coin-or/$Description_Slug/branch/$version)

## DOWNLOAD

### Docker image

There is a Docker image that provides $Description_ShortName, as well as other projects
in the [COIN-OR Optimization
Suite](https://github.com/coin-or/COIN-OR-OptimizationSuite) [here](https://hub.docker.com/repository/docker/coinor/coin-or-optimization-suite)

### Binaries

For newer releases, binaries will be made available as assets attached to
releases in Github
[here](https://github.com/coin-or/$Description_Slug/releases). Older binaries
are archived as part of $Description_Bintray_Package
[here](https://www.coin-or.org/download/binary/$Description_Bintray_Package).

 * *Linux*: On Debian/Ubuntu, $Description_ShortName is available in the package \`coinor-$lower_case\` and can be installed with apt. On Fedora, $Description_ShortName is available in the package \`coin-or-$Description_Slug\`.
 * *Windows*: The easiest way to get $Description_ShortName on Windows is to download an archive as described above.
 * *Mac OS X*: The easiest way to get $Description_ShortName on Mac OS X is through [Homebrew](https://brew.sh).
   * \`brew tap coin-or-tools/coinor\`
   * \`brew install coin-or-tools/coinor/$lower_case\`

Due to license incompatibilities, pre-compiled binaries lack some functionality.
If binaries are not available for your platform for the latest version and you would like to request them to be built and posted, feel free to let us know on the mailing list.

### Source

Source code can be obtained either by

 * Downloading a snapshot of the source code for the latest release version of $Description_ShortName from the
 [releases](https://github.com/coin-or/$Description_Slug/releases) page.
 * Cloning this repository from [Github](https://github.com/coin-or/$Description_Slug) or 
 * Using the [coinbrew](https://github.com/coin-or/coinbrew) script to get the project and all dependencies (recommended, see below).   

Below is a quick start guide for building on common platforms. More detailed
build instructions are
[here](https://coin-or.github.io/user_introduction.html).

## BUILDING from source

The quick start assumes you are in a bash shell. 

### Using \`coinbrew\`

To build $Description_ShortName from source, obtain the \`coinbrew\` script, do
\`\`\`
wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
chmod u+x coinbrew
./coinbrew fetch $Description_Slug@$version
./coinbrew build $Description_Slug
\`\`\`
For more detailed instructions on coinbrew, see https://coin-or.github.io/coinbrew.
The \`coinbrew\` script will fetch the additional projects specified in the Dependencies section of [config.yml](.coin-or/config.yml).

### Without \`coinbrew\` (Expert users)

 * Download the source code, e.g., by cloning the git repo https://github.com/coin-or/$Description_Slug
 * Download and install the source code for the dependencies listed in [config.yml](.coin-or/config.yml)
 * Build the code as follows (make sure to set PKG_CONFIG_PTH to install directory for dependencies).

\`\`\`
./configure -C
make
make test
make install
\`\`\`
"
}

#########################################################################
#########################################################################

function make_doxygen_info {
    echo "## Doxygen Documentation

If you have \`Doxygen\` available, you can build a HTML documentation by typing

\`make doxygen-docs\` 

in the build directory. If $Description_ShortName was built via \`coinbrew\`, then the build
directory will be \`./build/$Description_Slug/$version_num\` by default. The doxygen documentation main file
is found at \`<build-dir>/doxydoc/html/index.html\`.

If you don't have \`doxygen\` installed locally, you can use also find the
documentation [here](http://coin-or.github.io/$Description_Slug/Doxygen).
"
}

#########################################################################
#########################################################################

function make_links {
    echo "
## Project Links

 * [COIN-OR Initiative](http://www.coin-or.org/)
 * [Discussion formum](https://github.com/coin-or/$Description_Slug/discussions)
 * [Report a bug](https://github.com/coin-or/$Description_Slug/issues/new)
 * [Doxygen-generated html documentation](http://coin-or.github.io/$Description_Slug/Doxygen)
" 
}




